name: CI Example

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Run a simple script
        run: echo "Hello, GitHub Actions!"

      - name: Run tests (ignore if none found)
        run: |
          echo "Running tests..."
          python -m unittest discover || echo "No tests found â€” skipping"


      - name: Build the application
        run: |
          echo "Building the app..."
          npm install
          npm run build
